[project]
name = "control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "keyboard>=0.13.5",
    "numpy>=2.2.3",
    "pyserial>=3.5",
    "pyusb>=1.3.1",
    "scipy>=1.15.2",
]
